version: '2.1'
services:
  kafka-manager:
    build:
      context: .
      dockerfile: Dockerfile
    image: mmaia/kafka-manager:v1
    container_name: kafka-manager
    ports:
      - '9000:9000'
    mem_limit: 512m